name: Deploy Munson Pickles API

on:
  workflow_dispatch:

env:
AZURE_WEBAPP_NAME: "app-dotnet-app"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore ./MyFirstAPI.csproj
    
    - name: Build
      run: dotnet build ./MyFirstAPI.csproj --configuration Release --no-restore
    # publish
    - name: Publish
      run: dotnet publish ./MyFirstAPI.csproj --configuration Release --no-build --output ./publish

    # deploy to azure
    - name: Deploy to Azure Web App
    uses: azure/webapps-deploy@v2
    with:
      app-name: ${{env.AZURE_WEBAPP_NAME}}
      publish-profile: ${{secrets.API_PUBLISH_SECRET}}
      package: ./publish