name: Deploy Munson Pickles API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore ./MyFirstAPI.csproj
    
    - name: Build
      run: dotnet build ./MyFirstAPI.csproj --configuration Release --norestore




      
